<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PurchaseOrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_order_details')->delete();
        
        \DB::table('purchase_order_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'purchase_order_id' => 1,
                'item_id' => 2,
                'description' => NULL,
                'item_name' => 'iPhone 11 pro',
                'discount' => '2.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '59.94000000',
                'unit_price' => '999.00000000',
                'quantity_ordered' => '3.00000000',
                'quantity_received' => '3.00000000',
            ),
            1 => 
            array (
                'id' => 2,
                'purchase_order_id' => 1,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '3.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '32.76000000',
                'unit_price' => '546.00000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '2.00000000',
            ),
            2 => 
            array (
                'id' => 3,
                'purchase_order_id' => 1,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => '5.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '1.20000000',
                'unit_price' => '4.00000000',
                'quantity_ordered' => '6.00000000',
                'quantity_received' => '6.00000000',
            ),
            3 => 
            array (
                'id' => 4,
                'purchase_order_id' => 2,
                'item_id' => 9,
                'description' => NULL,
                'item_name' => 'Blender',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '70.00000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '2.00000000',
            ),
            4 => 
            array (
                'id' => 5,
                'purchase_order_id' => 2,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '910.00000000',
                'quantity_ordered' => '4.00000000',
                'quantity_received' => '3.00000000',
            ),
            5 => 
            array (
                'id' => 6,
                'purchase_order_id' => 3,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '46.20000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            6 => 
            array (
                'id' => 7,
                'purchase_order_id' => 3,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '1234.20000000',
                'quantity_ordered' => '5.00000000',
                'quantity_received' => '5.00000000',
            ),
            7 => 
            array (
                'id' => 8,
                'purchase_order_id' => 4,
                'item_id' => 13,
                'description' => NULL,
                'item_name' => 'Corn Flakes',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '5.20000000',
                'quantity_ordered' => '5.00000000',
                'quantity_received' => '0.00000000',
            ),
            8 => 
            array (
                'id' => 9,
                'purchase_order_id' => 4,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '9.20000000',
                'quantity_ordered' => '4.00000000',
                'quantity_received' => '0.00000000',
            ),
            9 => 
            array (
                'id' => 10,
                'purchase_order_id' => 5,
                'item_id' => 3,
                'description' => NULL,
                'item_name' => 'iPhone 11',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '556.00000000',
                'quantity_ordered' => '1.00000000',
                'quantity_received' => '0.00000000',
            ),
            10 => 
            array (
                'id' => 11,
                'purchase_order_id' => 5,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '520.00000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '0.00000000',
            ),
            11 => 
            array (
                'id' => 12,
                'purchase_order_id' => 5,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '0.00000000',
                'unit_price' => '22.40000000',
                'quantity_ordered' => '3.00000000',
                'quantity_received' => '0.00000000',
            ),
            12 => 
            array (
                'id' => 13,
                'purchase_order_id' => 6,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '10.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '733.04000000',
                'unit_price' => '1047.20000000',
                'quantity_ordered' => '7.00000000',
                'quantity_received' => '7.00000000',
            ),
            13 => 
            array (
                'id' => 14,
                'purchase_order_id' => 6,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '20.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '1638.00000000',
                'unit_price' => '910.00000000',
                'quantity_ordered' => '9.00000000',
                'quantity_received' => '9.00000000',
            ),
            14 => 
            array (
                'id' => 15,
                'purchase_order_id' => 7,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '10.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '733.04000000',
                'unit_price' => '1047.20000000',
                'quantity_ordered' => '7.00000000',
                'quantity_received' => '0.00000000',
            ),
            15 => 
            array (
                'id' => 16,
                'purchase_order_id' => 7,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '20.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '1638.00000000',
                'unit_price' => '910.00000000',
                'quantity_ordered' => '9.00000000',
                'quantity_received' => '0.00000000',
            ),
            16 => 
            array (
                'id' => 17,
                'purchase_order_id' => 8,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '10.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '273.00000000',
                'unit_price' => '546.00000000',
                'quantity_ordered' => '5.00000000',
                'quantity_received' => '3.00000000',
            ),
            17 => 
            array (
                'id' => 18,
                'purchase_order_id' => 9,
                'item_id' => 3,
                'description' => NULL,
                'item_name' => 'iPhone 11',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '695.00000000',
                'quantity_ordered' => '3.00000000',
                'quantity_received' => '3.00000000',
            ),
            18 => 
            array (
                'id' => 19,
                'purchase_order_id' => 9,
                'item_id' => 2,
                'description' => NULL,
                'item_name' => 'iPhone 11 pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '999.00000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '2.00000000',
            ),
            19 => 
            array (
                'id' => 20,
                'purchase_order_id' => 9,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '0.00000000',
                'unit_price' => '748.00000000',
                'quantity_ordered' => '1.00000000',
                'quantity_received' => '1.00000000',
            ),
            20 => 
            array (
                'id' => 27,
                'purchase_order_id' => 12,
                'item_id' => 9,
                'description' => NULL,
                'item_name' => 'Blender',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '1500.50000000',
                'quantity_ordered' => '4.00000000',
                'quantity_received' => '4.00000000',
            ),
            21 => 
            array (
                'id' => 28,
                'purchase_order_id' => 12,
                'item_id' => 13,
                'description' => NULL,
                'item_name' => 'Corn Flakes',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '2500.04000000',
                'quantity_ordered' => '3.00000000',
                'quantity_received' => '3.00000000',
            ),
            22 => 
            array (
                'id' => 29,
                'purchase_order_id' => 12,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '0.00000000',
                'unit_price' => '1500.04000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '2.00000000',
            ),
            23 => 
            array (
                'id' => 30,
                'purchase_order_id' => 13,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '46.20000000',
                'quantity_ordered' => '11.00000000',
                'quantity_received' => '11.00000000',
            ),
            24 => 
            array (
                'id' => 31,
                'purchase_order_id' => 13,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '1234.20000000',
                'quantity_ordered' => '5.00000000',
                'quantity_received' => '5.00000000',
            ),
            25 => 
            array (
                'id' => 32,
                'purchase_order_id' => 13,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '0.00000000',
                'unit_price' => '900.90000000',
                'quantity_ordered' => '7.00000000',
                'quantity_received' => '7.00000000',
            ),
            26 => 
            array (
                'id' => 33,
                'purchase_order_id' => 14,
                'item_id' => 9,
                'description' => NULL,
                'item_name' => 'Blender',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '1500.50000000',
                'quantity_ordered' => '4.00000000',
                'quantity_received' => '4.00000000',
            ),
            27 => 
            array (
                'id' => 34,
                'purchase_order_id' => 14,
                'item_id' => 13,
                'description' => NULL,
                'item_name' => 'Corn Flakes',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '2500.04000000',
                'quantity_ordered' => '3.00000000',
                'quantity_received' => '3.00000000',
            ),
            28 => 
            array (
                'id' => 35,
                'purchase_order_id' => 14,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => '0.00000000',
                'unit_price' => '1500.04000000',
                'quantity_ordered' => '2.00000000',
                'quantity_received' => '2.00000000',
            ),
            29 => 
            array (
                'id' => 36,
                'purchase_order_id' => 14,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'discount_amount' => '0.00000000',
                'unit_price' => '9.28000000',
                'quantity_ordered' => '16.00000000',
                'quantity_received' => '16.00000000',
            ),
            30 => 
            array (
                'id' => 46,
                'purchase_order_id' => 22,
                'item_id' => 9,
                'description' => NULL,
                'item_name' => 'Blender',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '50.00000000',
                'quantity_ordered' => '20.00000000',
                'quantity_received' => '20.00000000',
            ),
            31 => 
            array (
                'id' => 47,
                'purchase_order_id' => 22,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '28.00000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            32 => 
            array (
                'id' => 48,
                'purchase_order_id' => 23,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '748.00000000',
                'quantity_ordered' => '12.00000000',
                'quantity_received' => '12.00000000',
            ),
            33 => 
            array (
                'id' => 49,
                'purchase_order_id' => 23,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '650.00000000',
                'quantity_ordered' => '15.00000000',
                'quantity_received' => '15.00000000',
            ),
            34 => 
            array (
                'id' => 50,
                'purchase_order_id' => 24,
                'item_id' => 13,
                'description' => NULL,
                'item_name' => 'Corn Flakes',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '4.00000000',
                'quantity_ordered' => '100.00000000',
                'quantity_received' => '100.00000000',
            ),
            35 => 
            array (
                'id' => 51,
                'purchase_order_id' => 24,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '4.00000000',
                'quantity_ordered' => '30.00000000',
                'quantity_received' => '30.00000000',
            ),
            36 => 
            array (
                'id' => 52,
                'purchase_order_id' => 25,
                'item_id' => 2,
                'description' => NULL,
                'item_name' => 'iPhone 11 pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '999.00000000',
                'quantity_ordered' => '80.00000000',
                'quantity_received' => '80.00000000',
            ),
            37 => 
            array (
                'id' => 53,
                'purchase_order_id' => 26,
                'item_id' => 3,
                'description' => NULL,
                'item_name' => 'iPhone 11',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '695.00000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            38 => 
            array (
                'id' => 54,
                'purchase_order_id' => 26,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '28.00000000',
                'quantity_ordered' => '55.00000000',
                'quantity_received' => '55.00000000',
            ),
            39 => 
            array (
                'id' => 55,
                'purchase_order_id' => 27,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '546.00000000',
                'quantity_ordered' => '16.00000000',
                'quantity_received' => '16.00000000',
            ),
            40 => 
            array (
                'id' => 56,
                'purchase_order_id' => 28,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '650.00000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            41 => 
            array (
                'id' => 57,
                'purchase_order_id' => 28,
                'item_id' => 2,
                'description' => NULL,
                'item_name' => 'iPhone 11 pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '999.00000000',
                'quantity_ordered' => '15.00000000',
                'quantity_received' => '15.00000000',
            ),
            42 => 
            array (
                'id' => 58,
                'purchase_order_id' => 29,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '546.00000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            43 => 
            array (
                'id' => 59,
                'purchase_order_id' => 29,
                'item_id' => 9,
                'description' => NULL,
                'item_name' => 'Blender',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '50.00000000',
                'quantity_ordered' => '10.00000000',
                'quantity_received' => '10.00000000',
            ),
            44 => 
            array (
                'id' => 60,
                'purchase_order_id' => 30,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '650.00000000',
                'quantity_ordered' => '13.00000000',
                'quantity_received' => '13.00000000',
            ),
            45 => 
            array (
                'id' => 61,
                'purchase_order_id' => 30,
                'item_id' => 2,
                'description' => NULL,
                'item_name' => 'iPhone 11 pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '999.00000000',
                'quantity_ordered' => '15.00000000',
                'quantity_received' => '15.00000000',
            ),
            46 => 
            array (
                'id' => 62,
                'purchase_order_id' => 31,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '546.00000000',
                'quantity_ordered' => '15.00000000',
                'quantity_received' => '15.00000000',
            ),
            47 => 
            array (
                'id' => 63,
                'purchase_order_id' => 31,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '28.00000000',
                'quantity_ordered' => '80.00000000',
                'quantity_received' => '80.00000000',
            ),
            48 => 
            array (
                'id' => 64,
                'purchase_order_id' => 32,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => '0.00000000',
                'unit_price' => '748.00000000',
                'quantity_ordered' => '15.00000000',
                'quantity_received' => '15.00000000',
            ),
            49 => 
            array (
                'id' => 65,
                'purchase_order_id' => 32,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => '0.00000000',
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => '0.00000000',
                'unit_price' => '650.00000000',
                'quantity_ordered' => '1.00000000',
                'quantity_received' => '1.00000000',
            ),
        ));
        
        
    }
}