<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StockMovesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stock_moves')->delete();
        
        \DB::table('stock_moves')->insert(array (
            0 => 
            array (
                'id' => 2,
                'item_id' => 2,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_2',
                'note' => 'Added from initial stock',
                'quantity' => 10.0,
                'price' => 997.0,
            ),
            1 => 
            array (
                'id' => 3,
                'item_id' => 3,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_3',
                'note' => 'Added from initial stock',
                'quantity' => 20.0,
                'price' => 690.0,
            ),
            2 => 
            array (
                'id' => 4,
                'item_id' => 4,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_4',
                'note' => 'Added from initial stock',
                'quantity' => 20.0,
                'price' => 746.0,
            ),
            3 => 
            array (
                'id' => 5,
                'item_id' => 5,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_5',
                'note' => 'Added from initial stock',
                'quantity' => 10.0,
                'price' => 546.0,
            ),
            4 => 
            array (
                'id' => 6,
                'item_id' => 6,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_6',
                'note' => 'Added from initial stock',
                'quantity' => 5.0,
                'price' => 650.0,
            ),
            5 => 
            array (
                'id' => 7,
                'item_id' => 8,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_8',
                'note' => 'Added from initial stock',
                'quantity' => 30.0,
                'price' => 28.0,
            ),
            6 => 
            array (
                'id' => 8,
                'item_id' => 9,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_9',
                'note' => 'Added from initial stock',
                'quantity' => 50.0,
                'price' => 50.0,
            ),
            7 => 
            array (
                'id' => 9,
                'item_id' => 12,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_12',
                'note' => 'Added from initial stock',
                'quantity' => 30.0,
                'price' => 4.0,
            ),
            8 => 
            array (
                'id' => 10,
                'item_id' => 13,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_13',
                'note' => 'Added from initial stock',
                'quantity' => 50.0,
                'price' => 4.0,
            ),
            9 => 
            array (
                'id' => 11,
                'item_id' => 14,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_14',
                'note' => 'Added from initial stock',
                'quantity' => 10.0,
                'price' => 1680.0,
            ),
            10 => 
            array (
                'id' => 12,
                'item_id' => 15,
                'transaction_type_id' => NULL,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'store_in_15',
                'note' => 'Added from initial stock',
                'quantity' => 10.0,
                'price' => 1080.0,
            ),
            11 => 
            array (
                'id' => 13,
                'item_id' => 4,
                'transaction_type_id' => 9,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 14,
                'reference' => 'store_out_9',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 757.0,
            ),
            12 => 
            array (
                'id' => 14,
                'item_id' => 5,
                'transaction_type_id' => 9,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 15,
                'reference' => 'store_out_9',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 550.0,
            ),
            13 => 
            array (
                'id' => 16,
                'item_id' => 8,
                'transaction_type_id' => 14,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 19,
                'reference' => 'store_out_14',
                'note' => NULL,
                'quantity' => -4.0,
                'price' => 19.5,
            ),
            14 => 
            array (
                'id' => 17,
                'item_id' => 12,
                'transaction_type_id' => 14,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 20,
                'reference' => 'store_out_14',
                'note' => NULL,
                'quantity' => -5.0,
                'price' => 3.25,
            ),
            15 => 
            array (
                'id' => 18,
                'item_id' => 9,
                'transaction_type_id' => 16,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 23,
                'reference' => 'store_out_16',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 52.0,
            ),
            16 => 
            array (
                'id' => 19,
                'item_id' => 5,
                'transaction_type_id' => 16,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 24,
                'reference' => 'store_out_16',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 550.0,
            ),
            17 => 
            array (
                'id' => 20,
                'item_id' => 4,
                'transaction_type_id' => 18,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 27,
                'reference' => 'store_out_18',
                'note' => NULL,
                'quantity' => -6.0,
                'price' => 492.05,
            ),
            18 => 
            array (
                'id' => 21,
                'item_id' => 5,
                'transaction_type_id' => 18,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 28,
                'reference' => 'store_out_18',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 357.5,
            ),
            19 => 
            array (
                'id' => 22,
                'item_id' => 2,
                'transaction_type_id' => 22,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 32,
                'reference' => 'store_out_22',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 999.0,
            ),
            20 => 
            array (
                'id' => 23,
                'item_id' => 3,
                'transaction_type_id' => 22,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 33,
                'reference' => 'store_out_22',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 705.0,
            ),
            21 => 
            array (
                'id' => 24,
                'item_id' => 13,
                'transaction_type_id' => 22,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 34,
                'reference' => 'store_out_22',
                'note' => NULL,
                'quantity' => -10.0,
                'price' => 5.0,
            ),
            22 => 
            array (
                'id' => 25,
                'item_id' => 14,
                'transaction_type_id' => 26,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 38,
                'reference' => 'store_out_26',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 1105.0,
            ),
            23 => 
            array (
                'id' => 26,
                'item_id' => 8,
                'transaction_type_id' => 26,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 39,
                'reference' => 'store_out_26',
                'note' => NULL,
                'quantity' => -10.0,
                'price' => 19.5,
            ),
            24 => 
            array (
                'id' => 27,
                'item_id' => 6,
                'transaction_type_id' => 26,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 40,
                'reference' => 'store_out_26',
                'note' => NULL,
                'quantity' => -5.0,
                'price' => 455.0,
            ),
            25 => 
            array (
                'id' => 28,
                'item_id' => 10,
                'transaction_type_id' => 27,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 41,
                'reference' => 'store_out_27',
                'note' => NULL,
                'quantity' => -24.0,
                'price' => 80.0,
            ),
            26 => 
            array (
                'id' => 29,
                'item_id' => 2,
                'transaction_type_id' => 29,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 43,
                'reference' => 'store_out_29',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 999.0,
            ),
            27 => 
            array (
                'id' => 30,
                'item_id' => 3,
                'transaction_type_id' => 30,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 44,
                'reference' => 'store_out_30',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 705.0,
            ),
            28 => 
            array (
                'id' => 31,
                'item_id' => 2,
                'transaction_type_id' => 30,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 45,
                'reference' => 'store_out_30',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 999.0,
            ),
            29 => 
            array (
                'id' => 32,
                'item_id' => 9,
                'transaction_type_id' => 32,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 49,
                'reference' => 'store_out_32',
                'note' => NULL,
                'quantity' => -5.0,
                'price' => 52.0,
            ),
            30 => 
            array (
                'id' => 33,
                'item_id' => 12,
                'transaction_type_id' => 32,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 50,
                'reference' => 'store_out_32',
                'note' => NULL,
                'quantity' => -10.0,
                'price' => 5.0,
            ),
            31 => 
            array (
                'id' => 34,
                'item_id' => 13,
                'transaction_type_id' => 32,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 51,
                'reference' => 'store_out_32',
                'note' => NULL,
                'quantity' => -6.0,
                'price' => 5.0,
            ),
            32 => 
            array (
                'id' => 35,
                'item_id' => 13,
                'transaction_type_id' => 1,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_1',
                'note' => NULL,
                'quantity' => 20.0,
                'price' => 0.0,
            ),
            33 => 
            array (
                'id' => 36,
                'item_id' => 13,
                'transaction_type_id' => 1,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_3',
                'note' => NULL,
                'quantity' => -20.0,
                'price' => 0.0,
            ),
            34 => 
            array (
                'id' => 37,
                'item_id' => 9,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_2',
                'note' => NULL,
                'quantity' => 10.0,
                'price' => 0.0,
            ),
            35 => 
            array (
                'id' => 38,
                'item_id' => 9,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_3',
                'note' => NULL,
                'quantity' => -10.0,
                'price' => 0.0,
            ),
            36 => 
            array (
                'id' => 39,
                'item_id' => 9,
                'transaction_type_id' => 9,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 55,
                'reference' => 'store_out_55',
                'note' => NULL,
                'quantity' => -10.0,
                'price' => 0.0,
            ),
            37 => 
            array (
                'id' => 40,
                'item_id' => 2,
                'transaction_type_id' => 10,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 60,
                'reference' => 'store_out_60',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            38 => 
            array (
                'id' => 41,
                'item_id' => 3,
                'transaction_type_id' => 10,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 61,
                'reference' => 'store_out_61',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            39 => 
            array (
                'id' => 42,
                'item_id' => 13,
                'transaction_type_id' => 10,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 62,
                'reference' => 'store_out_62',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            40 => 
            array (
                'id' => 43,
                'item_id' => 9,
                'transaction_type_id' => 14,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 69,
                'reference' => 'store_out_69',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            41 => 
            array (
                'id' => 44,
                'item_id' => 13,
                'transaction_type_id' => 14,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 74,
                'reference' => 'store_out_74',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            42 => 
            array (
                'id' => 45,
                'item_id' => 4,
                'transaction_type_id' => 16,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 81,
                'reference' => 'store_out_81',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            43 => 
            array (
                'id' => 46,
                'item_id' => 9,
                'transaction_type_id' => 18,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 85,
                'reference' => 'store_out_85',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            44 => 
            array (
                'id' => 47,
                'item_id' => 12,
                'transaction_type_id' => 26,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 97,
                'reference' => 'store_out_97',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 0.0,
            ),
            45 => 
            array (
                'id' => 48,
                'item_id' => 13,
                'transaction_type_id' => 26,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-08',
                'user_id' => 1,
                'transaction_type_detail_id' => 98,
                'reference' => 'store_out_98',
                'note' => NULL,
                'quantity' => -2.0,
                'price' => 0.0,
            ),
            46 => 
            array (
                'id' => 49,
                'item_id' => 14,
                'transaction_type_id' => 34,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 100,
                'reference' => 'store_out_33',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 1105.0,
            ),
            47 => 
            array (
                'id' => 50,
                'item_id' => 8,
                'transaction_type_id' => 34,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 102,
                'reference' => 'store_out_33',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 19.5,
            ),
            48 => 
            array (
                'id' => 51,
                'item_id' => 6,
                'transaction_type_id' => 34,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 104,
                'reference' => 'store_out_33',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 455.0,
            ),
            49 => 
            array (
                'id' => 52,
                'item_id' => 12,
                'transaction_type_id' => 34,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 106,
                'reference' => 'store_out_33',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 3.25,
            ),
            50 => 
            array (
                'id' => 53,
                'item_id' => 13,
                'transaction_type_id' => 34,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 108,
                'reference' => 'store_out_33',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 3.25,
            ),
            51 => 
            array (
                'id' => 54,
                'item_id' => 2,
                'transaction_type_id' => 36,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 110,
                'reference' => 'store_out_35',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 999.0,
            ),
            52 => 
            array (
                'id' => 55,
                'item_id' => 3,
                'transaction_type_id' => 36,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 112,
                'reference' => 'store_out_35',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 705.0,
            ),
            53 => 
            array (
                'id' => 56,
                'item_id' => 13,
                'transaction_type_id' => 36,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 114,
                'reference' => 'store_out_35',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 5.0,
            ),
            54 => 
            array (
                'id' => 57,
                'item_id' => 9,
                'transaction_type_id' => 38,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 116,
                'reference' => 'store_out_37',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 52.0,
            ),
            55 => 
            array (
                'id' => 58,
                'item_id' => 5,
                'transaction_type_id' => 38,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 118,
                'reference' => 'store_out_37',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 550.0,
            ),
            56 => 
            array (
                'id' => 59,
                'item_id' => 4,
                'transaction_type_id' => 38,
                'transaction_type' => 'SALESINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-09',
                'user_id' => 1,
                'transaction_type_detail_id' => 120,
                'reference' => 'store_out_37',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 757.0,
            ),
            57 => 
            array (
                'id' => 60,
                'item_id' => 2,
                'transaction_type_id' => 1,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 1,
                'reference' => 'store_in_1',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 999.0,
            ),
            58 => 
            array (
                'id' => 61,
                'item_id' => 5,
                'transaction_type_id' => 1,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 2,
                'reference' => 'store_in_1',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 546.0,
            ),
            59 => 
            array (
                'id' => 62,
                'item_id' => 12,
                'transaction_type_id' => 1,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 3,
                'reference' => 'store_in_1',
                'note' => NULL,
                'quantity' => 6.0,
                'price' => 4.0,
            ),
            60 => 
            array (
                'id' => 63,
                'item_id' => 8,
                'transaction_type_id' => 2,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 4,
                'reference' => 'store_in_3',
                'note' => NULL,
                'quantity' => 10.0,
                'price' => 46.2,
            ),
            61 => 
            array (
                'id' => 64,
                'item_id' => 4,
                'transaction_type_id' => 2,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 5,
                'reference' => 'store_in_3',
                'note' => NULL,
                'quantity' => 5.0,
                'price' => 1234.2,
            ),
            62 => 
            array (
                'id' => 65,
                'item_id' => 3,
                'transaction_type_id' => 3,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 6,
                'reference' => 'store_in_9',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 695.0,
            ),
            63 => 
            array (
                'id' => 66,
                'item_id' => 2,
                'transaction_type_id' => 3,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 7,
                'reference' => 'store_in_9',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 999.0,
            ),
            64 => 
            array (
                'id' => 67,
                'item_id' => 4,
                'transaction_type_id' => 3,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 8,
                'reference' => 'store_in_9',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 748.0,
            ),
            65 => 
            array (
                'id' => 68,
                'item_id' => 9,
                'transaction_type_id' => 4,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 9,
                'reference' => 'store_in_12',
                'note' => NULL,
                'quantity' => 4.0,
                'price' => 1500.5,
            ),
            66 => 
            array (
                'id' => 69,
                'item_id' => 13,
                'transaction_type_id' => 4,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 10,
                'reference' => 'store_in_12',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 2500.04,
            ),
            67 => 
            array (
                'id' => 70,
                'item_id' => 12,
                'transaction_type_id' => 4,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 11,
                'reference' => 'store_in_12',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 1500.04,
            ),
            68 => 
            array (
                'id' => 71,
                'item_id' => 8,
                'transaction_type_id' => 5,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 12,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 46.2,
            ),
            69 => 
            array (
                'id' => 72,
                'item_id' => 4,
                'transaction_type_id' => 5,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 13,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 1234.2,
            ),
            70 => 
            array (
                'id' => 73,
                'item_id' => 5,
                'transaction_type_id' => 5,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 14,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 900.9,
            ),
            71 => 
            array (
                'id' => 74,
                'item_id' => 8,
                'transaction_type_id' => 6,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 15,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 46.2,
            ),
            72 => 
            array (
                'id' => 75,
                'item_id' => 4,
                'transaction_type_id' => 6,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 16,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 1234.2,
            ),
            73 => 
            array (
                'id' => 76,
                'item_id' => 5,
                'transaction_type_id' => 6,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 17,
                'reference' => 'store_in_13',
                'note' => NULL,
                'quantity' => 4.0,
                'price' => 900.9,
            ),
            74 => 
            array (
                'id' => 77,
                'item_id' => 9,
                'transaction_type_id' => 7,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 18,
                'reference' => 'store_in_14',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 1500.5,
            ),
            75 => 
            array (
                'id' => 78,
                'item_id' => 13,
                'transaction_type_id' => 7,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 19,
                'reference' => 'store_in_14',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 2500.04,
            ),
            76 => 
            array (
                'id' => 79,
                'item_id' => 12,
                'transaction_type_id' => 7,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 20,
                'reference' => 'store_in_14',
                'note' => NULL,
                'quantity' => 0.0,
                'price' => 1500.04,
            ),
            77 => 
            array (
                'id' => 80,
                'item_id' => 8,
                'transaction_type_id' => 7,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 21,
                'reference' => 'store_in_14',
                'note' => NULL,
                'quantity' => 16.0,
                'price' => 9.28,
            ),
            78 => 
            array (
                'id' => 81,
                'item_id' => 5,
                'transaction_type_id' => 8,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 22,
                'reference' => 'store_in_8',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 546.0,
            ),
            79 => 
            array (
                'id' => 82,
                'item_id' => 5,
                'transaction_type_id' => 9,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 23,
                'reference' => 'store_in_8',
                'note' => NULL,
                'quantity' => 1.0,
                'price' => 546.0,
            ),
            80 => 
            array (
                'id' => 83,
                'item_id' => 4,
                'transaction_type_id' => 10,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 24,
                'reference' => 'store_in_6',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 1047.2,
            ),
            81 => 
            array (
                'id' => 84,
                'item_id' => 6,
                'transaction_type_id' => 10,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 25,
                'reference' => 'store_in_6',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 910.0,
            ),
            82 => 
            array (
                'id' => 85,
                'item_id' => 4,
                'transaction_type_id' => 11,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 26,
                'reference' => 'store_in_6',
                'note' => NULL,
                'quantity' => 4.0,
                'price' => 1047.2,
            ),
            83 => 
            array (
                'id' => 86,
                'item_id' => 6,
                'transaction_type_id' => 11,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 27,
                'reference' => 'store_in_6',
                'note' => NULL,
                'quantity' => 7.0,
                'price' => 910.0,
            ),
            84 => 
            array (
                'id' => 87,
                'item_id' => 9,
                'transaction_type_id' => 12,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 28,
                'reference' => 'store_in_2',
                'note' => NULL,
                'quantity' => 2.0,
                'price' => 70.0,
            ),
            85 => 
            array (
                'id' => 88,
                'item_id' => 6,
                'transaction_type_id' => 12,
                'transaction_type' => 'PURCHINVOICE',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => 29,
                'reference' => 'store_in_2',
                'note' => NULL,
                'quantity' => 3.0,
                'price' => 910.0,
            ),
            86 => 
            array (
                'id' => 89,
                'item_id' => 3,
                'transaction_type_id' => 3,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_1',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => 3.0,
                'price' => 0.0,
            ),
            87 => 
            array (
                'id' => 90,
                'item_id' => 3,
                'transaction_type_id' => 3,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_2',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => -3.0,
                'price' => 0.0,
            ),
            88 => 
            array (
                'id' => 91,
                'item_id' => 12,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_1',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => 2.0,
                'price' => 0.0,
            ),
            89 => 
            array (
                'id' => 92,
                'item_id' => 12,
                'transaction_type_id' => 3,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_2',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => -2.0,
                'price' => 0.0,
            ),
            90 => 
            array (
                'id' => 93,
                'item_id' => 4,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_1',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => 4.0,
                'price' => 0.0,
            ),
            91 => 
            array (
                'id' => 94,
                'item_id' => 4,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_3',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => -6.0,
                'price' => 0.0,
            ),
            92 => 
            array (
                'id' => 95,
                'item_id' => 5,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_1',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => 1.0,
                'price' => 0.0,
            ),
            93 => 
            array (
                'id' => 96,
                'item_id' => 5,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_3',
                'note' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has su',
                'quantity' => -1.0,
                'price' => 0.0,
            ),
            94 => 
            array (
                'id' => 97,
                'item_id' => 4,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_2',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 6.0,
                'price' => 0.0,
            ),
            95 => 
            array (
                'id' => 98,
                'item_id' => 4,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_1',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => -6.0,
                'price' => 0.0,
            ),
            96 => 
            array (
                'id' => 99,
                'item_id' => 9,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKMOVEIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_from_2',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 4.0,
                'price' => 0.0,
            ),
            97 => 
            array (
                'id' => 100,
                'item_id' => 9,
                'transaction_type_id' => 6,
                'transaction_type' => 'STOCKMOVEOUT',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'moved_in_1',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => -4.0,
                'price' => 0.0,
            ),
            98 => 
            array (
                'id' => 101,
                'item_id' => 2,
                'transaction_type_id' => 1,
                'transaction_type' => 'STOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_1',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 6.0,
                'price' => 0.0,
            ),
            99 => 
            array (
                'id' => 102,
                'item_id' => 4,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_2',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 9.0,
                'price' => 0.0,
            ),
            100 => 
            array (
                'id' => 103,
                'item_id' => 12,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_2',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 3.0,
                'price' => 0.0,
            ),
            101 => 
            array (
                'id' => 104,
                'item_id' => 3,
                'transaction_type_id' => 3,
                'transaction_type' => 'STOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_3',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 6.0,
                'price' => 0.0,
            ),
            102 => 
            array (
                'id' => 105,
                'item_id' => 8,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_5',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 3.0,
                'price' => 0.0,
            ),
            103 => 
            array (
                'id' => 106,
                'item_id' => 5,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKIN',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_4',
                'note' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, co',
                'quantity' => 4.0,
                'price' => 0.0,
            ),
            104 => 
            array (
                'id' => 107,
                'item_id' => 4,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKOUT',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_out_4',
                'note' => 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, yo',
                'quantity' => -7.0,
                'price' => 0.0,
            ),
            105 => 
            array (
                'id' => 109,
                'item_id' => 9,
                'transaction_type_id' => 3,
                'transaction_type' => 'STOCKOUT',
                'location_id' => 2,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_out_3',
                'note' => 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don\'t look even slightly believable. If you are going to use a passage of Lorem Ipsum, yo',
                'quantity' => -6.0,
                'price' => 0.0,
            ),
            106 => 
            array (
                'id' => 110,
                'item_id' => 4,
                'transaction_type_id' => 1,
                'transaction_type' => 'STOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_1',
                'note' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions ',
                'quantity' => 10.0,
                'price' => 0.0,
            ),
            107 => 
            array (
                'id' => 111,
                'item_id' => 9,
                'transaction_type_id' => 2,
                'transaction_type' => 'STOCKIN',
                'location_id' => 3,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_in_2',
                'note' => 'The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions ',
                'quantity' => 9.0,
                'price' => 0.0,
            ),
            108 => 
            array (
                'id' => 112,
                'item_id' => 4,
                'transaction_type_id' => 4,
                'transaction_type' => 'STOCKOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_out_4',
                'note' => 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one ',
                'quantity' => -3.0,
                'price' => 0.0,
            ),
            109 => 
            array (
                'id' => 114,
                'item_id' => 4,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_out_5',
                'note' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i',
                'quantity' => -3.0,
                'price' => 0.0,
            ),
            110 => 
            array (
                'id' => 115,
                'item_id' => 6,
                'transaction_type_id' => 5,
                'transaction_type' => 'STOCKOUT',
                'location_id' => 1,
                'transaction_date' => '2020-04-13',
                'user_id' => 1,
                'transaction_type_detail_id' => NULL,
                'reference' => 'adjustment_out_5',
                'note' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor i',
                'quantity' => -2.0,
                'price' => 0.0,
            ),
            111 => 
            array (
                'id' => 116,
                'item_id' => 2,
                'transaction_type_id' => 42,
                'transaction_type' => 'POSINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => 137,
                'reference' => 'store_out_137',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 999.0,
            ),
            112 => 
            array (
                'id' => 117,
                'item_id' => 3,
                'transaction_type_id' => 42,
                'transaction_type' => 'POSINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => 138,
                'reference' => 'store_out_138',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 705.0,
            ),
            113 => 
            array (
                'id' => 118,
                'item_id' => 6,
                'transaction_type_id' => 42,
                'transaction_type' => 'POSINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => 139,
                'reference' => 'store_out_139',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 700.0,
            ),
            114 => 
            array (
                'id' => 119,
                'item_id' => 13,
                'transaction_type_id' => 42,
                'transaction_type' => 'POSINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => 140,
                'reference' => 'store_out_140',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 5.0,
            ),
            115 => 
            array (
                'id' => 120,
                'item_id' => 9,
                'transaction_type_id' => 42,
                'transaction_type' => 'POSINVOICE',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => 141,
                'reference' => 'store_out_141',
                'note' => NULL,
                'quantity' => -1.0,
                'price' => 52.0,
            ),
            116 => 
            array (
                'id' => 121,
                'item_id' => 16,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_16',
                'note' => 'Added from initial stock',
                'quantity' => 10,
                'price' => 190.0,
            ),
            117 => 
            array (
                'id' => 122,
                'item_id' => 17,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_17',
                'note' => 'Added from initial stock',
                'quantity' => 10,
                'price' => 250.0,
            ),
            118 => 
            array (
                'id' => 123,
                'item_id' => 18,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_18',
                'note' => 'Added from initial stock',
                'quantity' => 10,
                'price' => 595.0,
            ),
            119 => 
            array (
                'id' => 124,
                'item_id' => 19,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_19',
                'note' => 'Added from initial stock',
                'quantity' => 10,
                'price' => 299.0,
            ),
            120 => 
            array (
                'id' => 125,
                'item_id' => 20,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_20',
                'note' => 'Added from initial stock',
                'quantity' => 10,
                'price' => 20.0,
            ),
            121 => 
            array (
                'id' => 126,
                'item_id' => 21,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_21',
                'note' => 'Added from initial stock',
                'quantity' => 50,
                'price' => 1.0,
            ),
            122 => 
            array (
                'id' => 127,
                'item_id' => 22,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_22',
                'note' => 'Added from initial stock',
                'quantity' => 5,
                'price' => 120.0,
            ),
            123 => 
            array (
                'id' => 128,
                'item_id' => 23,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_23',
                'note' => 'Added from initial stock',
                'quantity' => 5,
                'price' => 120.0,
            ),
            124 => 
            array (
                'id' => 129,
                'item_id' => 24,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_23',
                'note' => 'Added from initial stock',
                'quantity' => 5,
                'price' => 15.0,
            ),
            125 => 
            array (
                'id' => 130,
                'item_id' => 25,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_23',
                'note' => 'Added from initial stock',
                'quantity' => 5,
                'price' => 8.0,
            ),
            126 => 
            array (
                'id' => 131,
                'item_id' => 26,
                'transaction_type_id' => null,
                'transaction_type' => 'INITIALSTOCKIN',
                'location_id' => 1,
                'transaction_date' => '2020-04-15',
                'user_id' => 1,
                'transaction_type_detail_id' => null,
                'reference' => 'store_in_23',
                'note' => 'Added from initial stock',
                'quantity' => 5,
                'price' => 5.0,
            )
        ));
        
        
    }
}