<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon;

class TasksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tasks')->delete();
        
        \DB::table('tasks')->insert(array (
            0 => 
            array (
                'id' => 131,
                'name' => 'Tax and discount calculation for invoice, quoation, purchase and POS',
                'description' => 'This  document  was  written  in  Microsoft  Word,  and  makes  heavy  use  of  styles.    The  styles dialog is initially located on the menu bar under the “Home” tab in MS Word.  It is recommended that the styles dialog be pulled off into a separate wind.',
                'priority_id' => 3,
                'created_at' => '2020-04-13 14:39:43',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => \Carbon::now()->subDays(3)->toDateTimeString(),
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 5,
                'related_to_type' => 1,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => '0.00',
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            1 => 
            array (
                'id' => 132,
                'name' => 'Inactive item categories are showing in item edit category drop down option.',
            'description' => 'The software design document (SDD) typically describes a software product\'s data design, architecture design, interface design, and procedural design. The content and organization of an SDD is specified by the IEEE 1016 standard.',
                'priority_id' => 3,
                'created_at' => '2020-04-13 14:42:38',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => NULL,
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 3,
                'related_to_type' => 2,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => '10.00',
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            2 => 
            array (
                'id' => 133,
                'name' => 'Improvement - Removal of PerfectMoney Payment Method from everywhere',
                'description' => 'PayMoney is an online payment gateway that ensures smooth and secure transaction from the pre-payment to the pay-out process. PayMoney is a much simpler & convenient way to send money online rather than going to bank or other ways. Just follow the PayMoney documentation to get started.',
                'priority_id' => 2,
                'created_at' => '2020-04-13 14:49:53',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => NULL,
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 2,
                'related_to_type' => 1,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => NULL,
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            3 => 
            array (
                'id' => 134,
                'name' => 'Bug Fix - Send money confirm incorrect amount and total display',
                'description' => 'PayMoney is an online payment gateway that ensures smooth and secure transaction from the pre-payment to the pay-out process. PayMoney is a much simpler & convenient way to send money online rather than going to bank or other ways. Just follow the PayMoney documentation to get started.',
                'priority_id' => 3,
                'created_at' => '2020-04-13 14:51:44',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => NULL,
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 4,
                'related_to_type' => 2,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => '12.00',
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            4 => 
            array (
                'id' => 135,
                'name' => 'New feature - selection of fiat currency wallets during user registration',
                'description' => 'A point of sale inventory management system allows a business owner to have more than one business location and adequately keep track of inventory at each without being present — no more worries about employee theft or pricing inconsistency between one location and another.',
                'priority_id' => 1,
                'created_at' => '2020-04-13 14:54:48',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => NULL,
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 4,
                'related_to_type' => 1,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => NULL,
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            5 => 
            array (
                'id' => 136,
                'name' => 'Property Inspection Request while users is submitting properties',
                'description' => 'Vacation Rental Marketplace by techvillage1 on CodeCanyon. Support/Help are provided by Support Ticket. Please send us e-mail for further info.',
                'priority_id' => 1,
                'created_at' => '2020-04-13 14:58:11',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => \Carbon::now()->toDateTimeString(),
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 3,
                'related_to_type' => 1,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => NULL,
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
            6 => 
            array (
                'id' => 137,
                'name' => 'Add host messages option by admin and update some task in vrent admin panel',
                'description' => 'vRent is an online vacation rental booking website designed particularly for holiday rentals all over the world. vRent is exclusively designed to satisfy the needs of the landlords who want to seriously make money by listing vacation rentals from all around the globe. vRent allows you to create your own vacation rental platform to help guests to find space for a cost.',
                'priority_id' => 1,
                'created_at' => '2020-04-13 15:01:11',
                'start_date' => \Carbon::now()->subDays(7)->toDateTimeString(),
                'due_date' => \Carbon::now()->toDateTimeString(),
                'finished_date' => NULL,
                'user_id' => 1,
                'task_status_id' => 1,
                'recurring_type' => NULL,
                'repeat_every' => NULL,
                'recurring' => 0,
                'recurring_ends_on' => NULL,
                'related_to_id' => 4,
                'related_to_type' => 2,
                'custom_recurring' => 0,
                'last_recurring_date' => NULL,
                'is_public' => 0,
                'is_billable' => 0,
                'is_billed' => 0,
                'invoice_id' => 0,
                'hourly_rate' => '5.00',
                'milestone_id' => NULL,
                'is_visible_to_customer' => 0,
                'deadline_notified' => 0,
            ),
        ));
        
        
    }
}