<?php

namespace Database\Seeders\ProductSeeds;

use Illuminate\Database\Seeder;

class PurchaseOrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_order_details')->delete();
        
        \DB::table('purchase_order_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'purchase_order_id' => 1,
                'item_id' => 2,
                'description' => 'null',
                'item_name' => 'iPhone 11 pro',
                'discount' => 2.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 59.94,
                'unit_price' => 999.0,
                'quantity_ordered' => 3.0,
                'quantity_received' => 3.0,
            ),
            1 => 
            array (
                'id' => 2,
                'purchase_order_id' => 1,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => 3.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 32.76,
                'unit_price' => 546.0,
                'quantity_ordered' => 2.0,
                'quantity_received' => 2.0,
            ),
            2 => 
            array (
                'id' => 3,
                'purchase_order_id' => 1,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => 5.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 1.2,
                'unit_price' => 4.0,
                'quantity_ordered' => 6.0,
                'quantity_received' => 6.0,
            ),
            3 => 
            array (
                'id' => 4,
                'purchase_order_id' => 2,
                'item_id' => 9,
                'description' => 'null',
                'item_name' => 'Blender',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 70.0,
                'quantity_ordered' => 2.0,
                'quantity_received' => 2.0,
            ),
            4 => 
            array (
                'id' => 5,
                'purchase_order_id' => 2,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 910.0,
                'quantity_ordered' => 4.0,
                'quantity_received' => 3.0,
            ),
            5 => 
            array (
                'id' => 6,
                'purchase_order_id' => 3,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 46.2,
                'quantity_ordered' => 10.0,
                'quantity_received' => 10.0,
            ),
            6 => 
            array (
                'id' => 7,
                'purchase_order_id' => 3,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 1234.2,
                'quantity_ordered' => 5.0,
                'quantity_received' => 5.0,
            ),
            7 => 
            array (
                'id' => 8,
                'purchase_order_id' => 4,
                'item_id' => 13,
                'description' => 'null',
                'item_name' => 'Corn Flakes',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 5.2,
                'quantity_ordered' => 5.0,
                'quantity_received' => 0.0,
            ),
            8 => 
            array (
                'id' => 9,
                'purchase_order_id' => 4,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 9.2,
                'quantity_ordered' => 4.0,
                'quantity_received' => 0.0,
            ),
            9 => 
            array (
                'id' => 10,
                'purchase_order_id' => 5,
                'item_id' => 3,
                'description' => 'null',
                'item_name' => 'iPhone 11',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 556.0,
                'quantity_ordered' => 1.0,
                'quantity_received' => 0.0,
            ),
            10 => 
            array (
                'id' => 11,
                'purchase_order_id' => 5,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 520.0,
                'quantity_ordered' => 2.0,
                'quantity_received' => 0.0,
            ),
            11 => 
            array (
                'id' => 12,
                'purchase_order_id' => 5,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 0.0,
                'unit_price' => 22.4,
                'quantity_ordered' => 3.0,
                'quantity_received' => 0.0,
            ),
            12 => 
            array (
                'id' => 13,
                'purchase_order_id' => 6,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => 10.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 733.04,
                'unit_price' => 1047.2,
                'quantity_ordered' => 7.0,
                'quantity_received' => 7.0,
            ),
            13 => 
            array (
                'id' => 14,
                'purchase_order_id' => 6,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => 20.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 1638.0,
                'unit_price' => 910.0,
                'quantity_ordered' => 9.0,
                'quantity_received' => 9.0,
            ),
            14 => 
            array (
                'id' => 15,
                'purchase_order_id' => 7,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => 10.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 733.04,
                'unit_price' => 1047.2,
                'quantity_ordered' => 7.0,
                'quantity_received' => 0.0,
            ),
            15 => 
            array (
                'id' => 16,
                'purchase_order_id' => 7,
                'item_id' => 6,
                'description' => NULL,
                'item_name' => 'Apple Watch Series 4',
                'discount' => 20.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 1638.0,
                'unit_price' => 910.0,
                'quantity_ordered' => 9.0,
                'quantity_received' => 0.0,
            ),
            16 => 
            array (
                'id' => 17,
                'purchase_order_id' => 8,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => 10.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 273.0,
                'unit_price' => 546.0,
                'quantity_ordered' => 5.0,
                'quantity_received' => 3.0,
            ),
            17 => 
            array (
                'id' => 18,
                'purchase_order_id' => 9,
                'item_id' => 3,
                'description' => 'null',
                'item_name' => 'iPhone 11',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 695.0,
                'quantity_ordered' => 3.0,
                'quantity_received' => 3.0,
            ),
            18 => 
            array (
                'id' => 19,
                'purchase_order_id' => 9,
                'item_id' => 2,
                'description' => 'null',
                'item_name' => 'iPhone 11 pro',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 999.0,
                'quantity_ordered' => 2.0,
                'quantity_received' => 2.0,
            ),
            19 => 
            array (
                'id' => 20,
                'purchase_order_id' => 9,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 0.0,
                'unit_price' => 748.0,
                'quantity_ordered' => 1.0,
                'quantity_received' => 1.0,
            ),
            20 => 
            array (
                'id' => 27,
                'purchase_order_id' => 12,
                'item_id' => 9,
                'description' => 'null',
                'item_name' => 'Blender',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 1500.5,
                'quantity_ordered' => 4.0,
                'quantity_received' => 4.0,
            ),
            21 => 
            array (
                'id' => 28,
                'purchase_order_id' => 12,
                'item_id' => 13,
                'description' => 'null',
                'item_name' => 'Corn Flakes',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 2500.04,
                'quantity_ordered' => 3.0,
                'quantity_received' => 3.0,
            ),
            22 => 
            array (
                'id' => 29,
                'purchase_order_id' => 12,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 0.0,
                'unit_price' => 1500.04,
                'quantity_ordered' => 2.0,
                'quantity_received' => 2.0,
            ),
            23 => 
            array (
                'id' => 30,
                'purchase_order_id' => 13,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 46.2,
                'quantity_ordered' => 11.0,
                'quantity_received' => 11.0,
            ),
            24 => 
            array (
                'id' => 31,
                'purchase_order_id' => 13,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 1234.2,
                'quantity_ordered' => 5.0,
                'quantity_received' => 5.0,
            ),
            25 => 
            array (
                'id' => 32,
                'purchase_order_id' => 13,
                'item_id' => 5,
                'description' => NULL,
                'item_name' => 'Huawei P30 Pro',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 0.0,
                'unit_price' => 900.9,
                'quantity_ordered' => 7.0,
                'quantity_received' => 7.0,
            ),
            26 => 
            array (
                'id' => 33,
                'purchase_order_id' => 14,
                'item_id' => 9,
                'description' => 'null',
                'item_name' => 'Blender',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'discount_amount' => 0.0,
                'unit_price' => 1500.5,
                'quantity_ordered' => 4.0,
                'quantity_received' => 4.0,
            ),
            27 => 
            array (
                'id' => 34,
                'purchase_order_id' => 14,
                'item_id' => 13,
                'description' => 'null',
                'item_name' => 'Corn Flakes',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'discount_amount' => 0.0,
                'unit_price' => 2500.04,
                'quantity_ordered' => 3.0,
                'quantity_received' => 3.0,
            ),
            28 => 
            array (
                'id' => 35,
                'purchase_order_id' => 14,
                'item_id' => 12,
                'description' => NULL,
                'item_name' => 'Oats',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'discount_amount' => 0.0,
                'unit_price' => 1500.04,
                'quantity_ordered' => 2.0,
                'quantity_received' => 2.0,
            ),
            29 => 
            array (
                'id' => 36,
                'purchase_order_id' => 14,
                'item_id' => 8,
                'description' => NULL,
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'discount_amount' => 0.0,
                'unit_price' => 9.28,
                'quantity_ordered' => 16.0,
                'quantity_received' => 16.0,
            ),
        ));
        
        
    }
}