<?php

namespace Database\Seeders\ProductSeeds;

use Illuminate\Database\Seeder;

class PurchaseOrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_orders')->delete();
        
        \DB::table('purchase_orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'supplier_id' => 5,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 1,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 5.0,
                'other_discount_type' => '%',
                'shipping_charge' => 30.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 3,
                'exchange_rate' => 1.0,
                'purchase_receive_type_id' => 1,
                'comments' => 'A statement outlining the essential characteristics and functions of an item, service, or materiel required to meet the minimum needs of the Government.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0001',
                'location_id' => 1,
                'payment_method_id' => NULL,
                'total' => 3918.57,
                'paid' => 3918.57,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 08:30:47',
                'updated_at' => '2020-04-13 15:04:53',
            ),
            1 => 
            array (
                'id' => 2,
                'supplier_id' => 1,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 10.0,
                'other_discount_type' => '%',
                'shipping_charge' => 50.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 2,
                'exchange_rate' => 1.4,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0002',
                'location_id' => 3,
                'payment_method_id' => NULL,
                'total' => 3541.04,
                'paid' => 0.0,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 10:11:59',
                'updated_at' => '2020-04-13 10:11:59',
            ),
            2 => 
            array (
                'id' => 3,
                'supplier_id' => 3,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 6.0,
                'other_discount_type' => '%',
                'shipping_charge' => 15.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 4,
                'exchange_rate' => 1.65,
                'purchase_receive_type_id' => 1,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0003',
                'location_id' => 2,
                'payment_method_id' => NULL,
                'total' => 6491.45,
                'paid' => 0.0,
                'payment_term_id' => 2,
                'created_at' => '2020-04-13 10:13:16',
                'updated_at' => '2020-04-13 10:13:16',
            ),
            3 => 
            array (
                'id' => 4,
                'supplier_id' => 2,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 4.0,
                'other_discount_type' => '%',
                'shipping_charge' => 20.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 2,
                'exchange_rate' => 1.3,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0004',
                'location_id' => 1,
                'payment_method_id' => NULL,
                'total' => 81.83,
                'paid' => 81.83,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 10:15:50',
                'updated_at' => '2020-04-13 15:09:02',
            ),
            4 => 
            array (
                'id' => 5,
                'supplier_id' => 4,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 1,
                'other_discount_amount' => 3.0,
                'other_discount_type' => '%',
                'shipping_charge' => 10.0,
                'custom_charge_title' => 'Misc. Charge',
                'custom_charge_amount' => 10.0,
                'currency_id' => 1,
                'exchange_rate' => 0.8,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0005',
                'location_id' => 2,
                'payment_method_id' => NULL,
                'total' => 1682.17,
                'paid' => 0.0,
                'payment_term_id' => 2,
                'created_at' => '2020-04-13 10:18:12',
                'updated_at' => '2020-04-13 10:18:12',
            ),
            5 => 
            array (
                'id' => 6,
                'supplier_id' => 2,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 1,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 1,
                'other_discount_amount' => 30.0,
                'other_discount_type' => '%',
                'shipping_charge' => 90.0,
                'custom_charge_title' => 'Air charge',
                'custom_charge_amount' => 20.0,
                'currency_id' => 2,
                'exchange_rate' => 1.4,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0006',
                'location_id' => 1,
                'payment_method_id' => NULL,
                'total' => 9612.88,
                'paid' => 0.0,
                'payment_term_id' => 3,
                'created_at' => '2020-04-13 10:20:11',
                'updated_at' => '2020-04-13 10:20:11',
            ),
            6 => 
            array (
                'id' => 7,
                'supplier_id' => 2,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 1,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 1,
                'other_discount_amount' => 30.0,
                'other_discount_type' => '%',
                'shipping_charge' => 90.0,
                'custom_charge_title' => 'Air charge',
                'custom_charge_amount' => 20.0,
                'currency_id' => 2,
                'exchange_rate' => 1.4,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0007',
                'location_id' => 1,
                'payment_method_id' => NULL,
                'total' => 9612.88,
                'paid' => 9612.88,
                'payment_term_id' => 3,
                'created_at' => '2020-04-13 10:20:23',
                'updated_at' => '2020-04-13 15:06:20',
            ),
            7 => 
            array (
                'id' => 8,
                'supplier_id' => 5,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 1,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 8.0,
                'other_discount_type' => '%',
                'shipping_charge' => 12.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 3,
                'exchange_rate' => 1.0,
                'purchase_receive_type_id' => 2,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0008',
                'location_id' => 2,
                'payment_method_id' => NULL,
                'total' => 2335.23,
                'paid' => 0.0,
                'payment_term_id' => 2,
                'created_at' => '2020-04-13 10:22:21',
                'updated_at' => '2020-04-13 10:22:21',
            ),
            8 => 
            array (
                'id' => 9,
                'supplier_id' => 5,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'after',
                'tax_type' => 'inclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 10.0,
                'other_discount_type' => '%',
                'shipping_charge' => 15.0,
                'custom_charge_title' => NULL,
                'custom_charge_amount' => 0.0,
                'currency_id' => 3,
                'exchange_rate' => 1.0,
                'purchase_receive_type_id' => 1,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0009',
                'location_id' => 3,
                'payment_method_id' => NULL,
                'total' => 4362.9,
                'paid' => 0.0,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 10:24:47',
                'updated_at' => '2020-04-13 10:24:47',
            ),
            9 => 
            array (
                'id' => 12,
                'supplier_id' => 4,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 1,
                'other_discount_amount' => 3.0,
                'other_discount_type' => '%',
                'shipping_charge' => 25.0,
                'custom_charge_title' => 'Misc. Charge',
                'custom_charge_amount' => 30.0,
                'currency_id' => 1,
                'exchange_rate' => 0.01,
                'purchase_receive_type_id' => 1,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0010',
                'location_id' => 3,
                'payment_method_id' => NULL,
                'total' => 16507.68,
                'paid' => 16507.68,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 10:26:52',
                'updated_at' => '2020-04-13 15:08:36',
            ),
            10 => 
            array (
                'id' => 13,
                'supplier_id' => 3,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 0,
                'other_discount_amount' => 0.0,
                'other_discount_type' => '%',
                'shipping_charge' => 15.0,
                'custom_charge_title' => '',
                'custom_charge_amount' => 0.0,
                'currency_id' => 4,
                'exchange_rate' => 1.65,
                'purchase_receive_type_id' => 1,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0011',
                'location_id' => 2,
                'payment_method_id' => NULL,
                'total' => 13387.66,
                'paid' => 0.0,
                'payment_term_id' => 2,
                'created_at' => '2020-04-13 10:28:23',
                'updated_at' => '2020-04-13 10:29:17',
            ),
            11 => 
            array (
                'id' => 14,
                'supplier_id' => 4,
                'user_id' => 1,
                'invoice_type' => 'quantity',
                'discount_on' => 'before',
                'tax_type' => 'exclusive',
                'has_tax' => 1,
                'has_description' => 1,
                'has_item_discount' => 0,
                'has_hsn' => 0,
                'has_other_discount' => 0,
                'has_shipping_charge' => 1,
                'has_custom_charge' => 1,
                'other_discount_amount' => 0.0,
                'other_discount_type' => '%',
                'shipping_charge' => 25.0,
                'custom_charge_title' => 'Misc. Charge',
                'custom_charge_amount' => 30.0,
                'currency_id' => 1,
                'exchange_rate' => 0.01,
                'purchase_receive_type_id' => 1,
                'comments' => 'Purchase description means the words used in a solicitation to describe the supplies, services, or construction to be purchased, and includes specifications attached to or made a part of the solicitation.',
                'has_comment' => 1,
                'order_date' => '2020-04-13',
                'reference' => 'PO-0012',
                'location_id' => 3,
                'payment_method_id' => NULL,
                'total' => 17042.46,
                'paid' => 17042.46,
                'payment_term_id' => 1,
                'created_at' => '2020-04-13 10:29:47',
                'updated_at' => '2020-04-13 15:09:40',
            ),
        ));
        
        
    }
}