<?php

namespace Database\Seeders\ProductSeeds;

use Illuminate\Database\Seeder;

class SaleOrderDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sale_order_details')->delete();
        
        \DB::table('sale_order_details')->insert(array (
            0 => 
            array (
                'id' => 9,
                'sale_order_id' => 6,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock.',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 30.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:09:19',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 10,
                'sale_order_id' => 6,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:09:19',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 11,
                'sale_order_id' => 6,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 700.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 12:09:19',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 14,
                'sale_order_id' => 9,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:13:35',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 15,
                'sale_order_id' => 9,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has a OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:13:36',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 19,
                'sale_order_id' => 14,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 4.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:17:08',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 20,
                'sale_order_id' => 14,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 5.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:17:09',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 23,
                'sale_order_id' => 16,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:18:48',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 24,
                'sale_order_id' => 16,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:18:48',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 27,
                'sale_order_id' => 18,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 492.05,
                'quantity_sent' => 0.0,
                'quantity' => 6.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:20:35',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 28,
                'sale_order_id' => 18,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 357.5,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:20:35',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 32,
                'sale_order_id' => 22,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:23:37',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 33,
                'sale_order_id' => 22,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:23:37',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 34,
                'sale_order_id' => 22,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 12:23:37',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 38,
                'sale_order_id' => 26,
                'item_id' => 14,
                'description' => 'MacBook Pro has a high-resolution, LED-backlit glossy widescreen display.',
                'item_name' => 'Mac Book Pro',
                'unit_price' => 1105.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 12:25:34',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 39,
                'sale_order_id' => 26,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 12:25:35',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 40,
                'sale_order_id' => 26,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 455.0,
                'quantity_sent' => 0.0,
                'quantity' => 5.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 12:25:35',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 55,
                'sale_order_id' => 9,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 12:56:19',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 60,
                'sale_order_id' => 10,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-08 01:02:26',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 61,
                'sale_order_id' => 10,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-08 01:02:27',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 62,
                'sale_order_id' => 10,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:02:27',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 69,
                'sale_order_id' => 14,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 33.8,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:05:00',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 70,
                'sale_order_id' => 13,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 4.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-08 01:07:19',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 71,
                'sale_order_id' => 13,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 5.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-08 01:07:19',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 72,
                'sale_order_id' => 13,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 33.8,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:07:19',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 73,
                'sale_order_id' => 13,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-08 01:07:19',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 74,
                'sale_order_id' => 14,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-08 01:07:19',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 75,
                'sale_order_id' => 5,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-08 01:09:14',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 76,
                'sale_order_id' => 5,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has a OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-08 01:09:14',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 77,
                'sale_order_id' => 5,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:09:14',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 78,
                'sale_order_id' => 15,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-08 01:09:41',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 79,
                'sale_order_id' => 15,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-08 01:09:41',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 80,
                'sale_order_id' => 15,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:09:41',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 81,
                'sale_order_id' => 16,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:09:41',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 85,
                'sale_order_id' => 18,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 33.8,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:10:24',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 86,
                'sale_order_id' => 21,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-08 01:11:47',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 87,
                'sale_order_id' => 21,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-08 01:11:47',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 88,
                'sale_order_id' => 21,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-08 01:11:47',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 92,
                'sale_order_id' => 25,
                'item_id' => 14,
                'description' => 'MacBook Pro has a high-resolution, LED-backlit glossy widescreen display.',
                'item_name' => 'Mac Book Pro',
                'unit_price' => 1105.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 93,
                'sale_order_id' => 25,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 10.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 94,
                'sale_order_id' => 25,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 455.0,
                'quantity_sent' => 0.0,
                'quantity' => 5.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 95,
                'sale_order_id' => 25,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed.',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 96,
                'sale_order_id' => 25,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 5,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 97,
                'sale_order_id' => 26,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed.',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 98,
                'sale_order_id' => 26,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 5,
                'created_at' => '2020-04-09 03:08:24',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 99,
                'sale_order_id' => 33,
                'item_id' => 14,
                'description' => 'MacBook Pro has a high-resolution, LED-backlit glossy widescreen display.',
                'item_name' => 'Mac Book Pro',
                'unit_price' => 1105.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:10:32',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 100,
                'sale_order_id' => 34,
                'item_id' => 14,
                'description' => 'MacBook Pro has a high-resolution, LED-backlit glossy widescreen display.',
                'item_name' => 'Mac Book Pro',
                'unit_price' => 1105.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 101,
                'sale_order_id' => 33,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 3.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 102,
                'sale_order_id' => 34,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 19.5,
                'quantity_sent' => 0.0,
                'quantity' => 3.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 103,
                'sale_order_id' => 33,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 455.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 104,
                'sale_order_id' => 34,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 455.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 105,
                'sale_order_id' => 33,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed.',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 106,
                'sale_order_id' => 34,
                'item_id' => 12,
                'description' => 'Oats are annual grasses belonging to the genus Avena, in the family Poaceae and are grown primarily for use as livestock feed.',
                'item_name' => 'Oats',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 4,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 107,
                'sale_order_id' => 33,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 5,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 108,
                'sale_order_id' => 34,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 3.25,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 5,
                'created_at' => '2020-04-09 03:10:33',
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 109,
                'sale_order_id' => 35,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 110,
                'sale_order_id' => 36,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 111,
                'sale_order_id' => 35,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 112,
                'sale_order_id' => 36,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 113,
                'sale_order_id' => 35,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 114,
                'sale_order_id' => 36,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:11:25',
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 115,
                'sale_order_id' => 37,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 116,
                'sale_order_id' => 38,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 117,
                'sale_order_id' => 37,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 118,
                'sale_order_id' => 38,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 119,
                'sale_order_id' => 37,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 120,
                'sale_order_id' => 38,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 757.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:12:00',
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 121,
                'sale_order_id' => 39,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:14:14',
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 122,
                'sale_order_id' => 39,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:14:14',
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 123,
                'sale_order_id' => 39,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:14:14',
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 124,
                'sale_order_id' => 39,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 700.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 4,
                'created_at' => '2020-04-09 03:14:14',
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 125,
                'sale_order_id' => 39,
                'item_id' => 8,
                'description' => 'A speaker with alarm clock.',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 30.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 5,
                'created_at' => '2020-04-09 03:14:14',
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 126,
                'sale_order_id' => 40,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 1,
                'created_at' => '2020-04-09 09:14:51',
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 127,
                'sale_order_id' => 40,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 2,
                'created_at' => '2020-04-09 09:14:52',
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 128,
                'sale_order_id' => 40,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 550.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 3,
                'created_at' => '2020-04-09 09:14:52',
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 129,
                'sale_order_id' => 40,
                'item_id' => 6,
                'description' => 'The Apple Watch Series 4 runs Apple\'s new WatchOS 5 operating system. It comes along with a variety of improvements, like enhanced fitness and health tracking, a walkie-talkie mode, and more.',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 700.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 4,
                'created_at' => '2020-04-09 09:14:52',
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 130,
                'sale_order_id' => 40,
                'item_id' => 8,
                'description' => 'A  speaker with alarm clock.',
                'item_name' => 'Havit Alarm Clock Wireless Speaker',
                'unit_price' => 30.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => NULL,
                'sorting_no' => 5,
                'created_at' => '2020-04-09 09:14:52',
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 131,
                'sale_order_id' => 7,
                'item_id' => 2,
                'description' => 'The iPhone 11 Pro is Apple\'s most powerful phone that comes in a one-hand-friendly size.',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:32:24',
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 132,
                'sale_order_id' => 7,
                'item_id' => 3,
            'description' => 'The phone is powered by Hexa Core (2.65 GHz, Dual-core, Lightning + 1.8 GHz, Quad-core, Thunder) processor.',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:32:24',
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 133,
                'sale_order_id' => 7,
                'item_id' => 13,
                'description' => 'Corn flakes are a packaged cereal product formed from small toasted flakes of corn, usually served cold with milk and sometimes sugar.',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:32:24',
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 134,
                'sale_order_id' => 17,
                'item_id' => 4,
                'description' => 'The phone comes with a 6.10-inch touchscreen display and an aspect ratio of 19:9. Samsung Galaxy S10 is powered by a 1.9GHz octa-core Samsung Exynos 9820 processor. It comes with 8GB of RAM.',
                'item_name' => 'Samsung Galaxy S10',
                'unit_price' => 492.05,
                'quantity_sent' => 0.0,
                'quantity' => 6.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 1,
                'created_at' => '2020-04-09 03:34:36',
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 135,
                'sale_order_id' => 17,
                'item_id' => 5,
                'description' => 'Huawei P30 Pro smartphone has an OLED display.',
                'item_name' => 'Huawei P30 Pro',
                'unit_price' => 357.5,
                'quantity_sent' => 0.0,
                'quantity' => 2.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 2,
                'created_at' => '2020-04-09 03:34:36',
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 136,
                'sale_order_id' => 17,
                'item_id' => 9,
            'description' => 'A blender (sometimes called a liquidizer in British English) is a kitchen and laboratory appliance used to mix, purée, or emulsify food and other substances.',
                'item_name' => 'Blender',
                'unit_price' => 33.8,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '%',
                'hsn' => '',
                'sorting_no' => 3,
                'created_at' => '2020-04-09 03:34:36',
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 137,
                'sale_order_id' => 42,
                'item_id' => 2,
                'description' => '',
                'item_name' => 'iPhone 11 pro',
                'unit_price' => 999.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '$',
                'hsn' => '',
                'sorting_no' => 0,
                'created_at' => '2020-04-15 12:40:50',
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 138,
                'sale_order_id' => 42,
                'item_id' => 3,
                'description' => '',
                'item_name' => 'iPhone 11',
                'unit_price' => 705.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '$',
                'hsn' => '',
                'sorting_no' => 0,
                'created_at' => '2020-04-15 12:40:50',
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 139,
                'sale_order_id' => 42,
                'item_id' => 6,
                'description' => '',
                'item_name' => 'Apple Watch Series 4',
                'unit_price' => 700.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '$',
                'hsn' => '',
                'sorting_no' => 0,
                'created_at' => '2020-04-15 12:40:51',
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 140,
                'sale_order_id' => 42,
                'item_id' => 13,
                'description' => '',
                'item_name' => 'Corn Flakes',
                'unit_price' => 5.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '$',
                'hsn' => '',
                'sorting_no' => 0,
                'created_at' => '2020-04-15 12:40:51',
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 141,
                'sale_order_id' => 42,
                'item_id' => 9,
                'description' => '',
                'item_name' => 'Blender',
                'unit_price' => 52.0,
                'quantity_sent' => 0.0,
                'quantity' => 1.0,
                'discount_amount' => 0.0,
                'discount' => 0.0,
                'discount_type' => '$',
                'hsn' => '',
                'sorting_no' => 0,
                'created_at' => '2020-04-15 12:40:51',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}